<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>goat</Authors>
    <Company></Company>
    <Version>1.0.0.4</Version>
    <Description>Remove letterboxing from cutscenes on ultrawide monitors.</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/goaaats/Dalamud.FullscreenCutscenes</PackageProjectUrl>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
